#!/bin/sh -e

# Check if AWS CLI is installed and callable
if ! command -v aws >/dev/null 2>&1; then
    echo "Missing module: AWS CLI"
    exit 1
fi

# Check if okta-aws-cli is installed and callable
if ! command -v okta-aws-cli >/dev/null 2>&1; then
    echo "Missing module: okta-aws-cli. https://github.com/okta/okta-aws-cli?tab=readme-ov-file#installation"
    exit 1
fi

# set variables
refresh=${2:-1}
refresh_secs=$(($refresh*3600))
now=$(date +%s)
FORCE=${FORCE:-0}

if [ -f $HOME/.aws-mfa-login.timestamp ] ; then
    ts=$(cat $HOME/.aws-mfa-login.timestamp)
    age=$(($now-$ts))
else
    age=0
fi

if [ $age -eq 0 -o $age -gt $refresh_secs -o $FORCE -eq 1 ] ; then
    # Maximum 3 attempts before script exits
    attempt=0
    while [ $attempt -lt 3 ]
    do
        okta-aws-cli --profile mfa
        if [ $? -eq 0 ]; then
            # Update timestamp file
            date +%s > $HOME/.aws-mfa-login.timestamp
            break
        else
            echo "Failed to get session token, please try again."
            attempt=$((attempt+1))
        fi
    done
    if [ $attempt -eq 3 ]; then
        echo "Maximum attempts reached. Exiting."
        exit 1
    fi
else
    echo ""
    echo "Credentials are still valid. $(( ($refresh_secs - $age) / 60 )) minutes before expiration."
fi
